install:
  - cmd: java -version
  - cmd: echo %username%
  - cmd: CACLS C:\Users\appveyor\AppData\Local\Temp /g %username%:F
  - mvn clean install

test_script:
  - mvn test -B 
  - mvn clean -Pstrict compile test-compile -B

cache:
  - '%HOMEPATH%\.m2' 

build: off